# Generated by Django 3.2.5 on 2021-07-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('seaport_code', models.CharField(max_length=50)),
                ('seaport_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city_tbl',
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('size', models.IntegerField()),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'container_type_tbl',
            },
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='shipment_app.city')),
                ('orgin_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orgin', to='shipment_app.city')),
            ],
            options={
                'db_table': 'routing_tbl',
            },
        ),
        migrations.CreateModel(
            name='ShipmentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('price', models.PositiveBigIntegerField()),
                ('routing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.routing')),
                ('type_container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.containertype')),
            ],
            options={
                'db_table': 'shipment_info_tbl',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.shipmentinfo')),
            ],
            options={
                'db_table': 'booking_tbl',
            },
        ),
    ]
