# Generated by Django 3.2.5 on 2021-08-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0003_auto_20210801_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentinfo',
            name='routing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.routing'),
        ),
        migrations.AlterField(
            model_name='shipmentinfo',
            name='type_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment_app.containertype'),
        ),
    ]
