# Generated by Django 3.2.5 on 2021-08-01 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0004_auto_20210801_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routing',
            name='destination_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_set', to='shipment_app.city'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='orgin_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgin_set', to='shipment_app.city'),
        ),
    ]
