# Generated by Django 3.2.5 on 2021-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0005_auto_20210801_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
