# Generated by Django 3.2.5 on 2021-08-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0006_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='insert_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
