# Generated by Django 3.2.5 on 2021-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Tên'),
        ),
    ]
