# Generated by Django 3.2.5 on 2021-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210804_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='phone_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Mã điện thoại'),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Số điện thoại'),
        ),
    ]
